//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurAffinityClassifier.App.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FurAffinityClassifier.App.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Fur Affinity Classifier
        ///Usage : FurAffinityClassifier.App.Console [option] [param]
        ///
        ///option:
        ///  (empty)[TAB]Execute classification
        ///  --help[TAB][TAB]Show this help
        ///  --version[TAB][TAB]Show version
        ///  --show-setting[TAB]Show setting
        ///  --change-setting[TAB]Change setting ([param] needed)
        ///
        ///param:
        ///  from-folder=[path][TAB][TAB]Set source folder
        ///  to-folder=[path][TAB][TAB]Set destination folder
        ///  create-folder=[True|False][TAB]Set create folder if not exist
        ///  overwrite=[True|False][TAB]Set overwrite [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid option.
        ///Type &apos;FuraffinityClassifier.App.Console --help&apos; to see usage. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidOption {
            get {
                return ResourceManager.GetString("InvalidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Classified files:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageClassifyFileClassifiedFiles {
            get {
                return ResourceManager.GetString("MessageClassifyFileClassifiedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File classification completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageClassifyFileDone {
            get {
                return ResourceManager.GetString("MessageClassifyFileDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Found files:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageClassifyFileFoundFiles {
            get {
                return ResourceManager.GetString("MessageClassifyFileFoundFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target files:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageClassifyFileTargetFiles {
            get {
                return ResourceManager.GetString("MessageClassifyFileTargetFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting is Invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageInvalidSetting {
            get {
                return ResourceManager.GetString("MessageInvalidSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   From : {0}
        ///To : {1}
        ///Create folder if not exest : {2}
        ///Overwrite if exist : {3}
        ///Classify as : {4} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageShowSetting {
            get {
                return ResourceManager.GetString("MessageShowSetting", resourceCulture);
            }
        }
    }
}
