//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurAffinityClassifier.App.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FurAffinityClassifier.App.Wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Classification setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClassificationSetting {
            get {
                return ResourceManager.GetString("ClassificationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Classify as に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClassifyAs {
            get {
                return ResourceManager.GetString("ClassifyAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create folder if not exist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateFolderIfNotExist {
            get {
                return ResourceManager.GetString("CreateFolderIfNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataGridHeaderFolder {
            get {
                return ResourceManager.GetString("DataGridHeaderFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataGridHeaderId {
            get {
                return ResourceManager.GetString("DataGridHeaderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMesageInvalidSetting {
            get {
                return ResourceManager.GetString("DialogMesageInvalidSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Classified files:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageClassifyFileClassifiedFiles {
            get {
                return ResourceManager.GetString("DialogMessageClassifyFileClassifiedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File classification completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageClassifyFileDone {
            get {
                return ResourceManager.GetString("DialogMessageClassifyFileDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Found files:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageClassifyFileFoundFiles {
            get {
                return ResourceManager.GetString("DialogMessageClassifyFileFoundFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target files:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageClassifyFileTargetFiles {
            get {
                return ResourceManager.GetString("DialogMessageClassifyFileTargetFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting save completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageSaveSettingDone {
            get {
                return ResourceManager.GetString("DialogMessageSaveSettingDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error occurred while save setting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageSaveSettingError {
            get {
                return ResourceManager.GetString("DialogMessageSaveSettingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Classification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogTitleClassifyFile {
            get {
                return ResourceManager.GetString("DialogTitleClassifyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogTitleSaveSetting {
            get {
                return ResourceManager.GetString("DialogTitleSaveSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogTitleSelectFolder {
            get {
                return ResourceManager.GetString("DialogTitleSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FolderSetting {
            get {
                return ResourceManager.GetString("FolderSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   From: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FromFolder {
            get {
                return ResourceManager.GetString("FromFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overwrite if exist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OverwriteIfExist {
            get {
                return ResourceManager.GetString("OverwriteIfExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveSetting {
            get {
                return ResourceManager.GetString("SaveSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchWatermark {
            get {
                return ResourceManager.GetString("SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToFolder {
            get {
                return ResourceManager.GetString("ToFolder", resourceCulture);
            }
        }
    }
}
